Question 1: Array Creation and Manipulation

In [2]:
import numpy as np


In [ ]:
##Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
##Q1.2: Create an array of 8 zeros using np.zeros()

zeros_array = np.zeros(8)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
##Q1.3: Create an array of 6 ones using np.ones()

ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [ ]:
##Q1.4: Create an array with values from 0 to 15 using np.arange()

array_15 = np.arange(16)
print(array_15)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
###Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

evenly_spaced_array = np.linspace(0, 100, 8)
print(evenly_spaced_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


Question 2: Array Attributes and Information


In [9]:
##Q2.1: What is the shape of the banking_data array?

print(f"Shape: {banking_data.shape}")

Shape: (3, 3)


In [10]:
##Q2.2: What is the data type of the banking_data array?

print(f"Data Type: {banking_data.dtype}")

Data Type: int64


In [11]:
##Q2.3: What is the size (total number of elements) of the banking_data array?

print(f"Size: {banking_data.size}")

Size: 9


In [12]:
##Q2.4: What is the number of dimensions of the banking_data array?

print(f"Number of Dimensions: {banking_data.ndim}")

Number of Dimensions: 2


In [17]:
##Q2.5: What is the memory size of the banking_data array in bytes?

print(f"memory_size : {banking_data.nbytes}")

memory_size : 72


Question 3: Indexing and Slicing

In [18]:
##Q3.1: Extract the first row of banking_data

first_row = banking_data[0 : 1]
print(first_row)

[[100 200 300]]


In [19]:
##Q3.2: Extract the last row of banking_data

last_row = banking_data[-1:]
print(last_row)

[[120 220 320]]


In [20]:
##Q3.3: Extract the Account_Balance column (column index 1

account_balance = banking_data[:, 1]
print(account_balance)

[200 250 220]


In [22]:
##Q3.4: Extract the first 4 rows and first 3 columns

first_4_rows_first_3_columns = banking_data[:4, :3]
print(first_4_rows_first_3_columns)

[[100 200 300]
 [150 250 350]
 [120 220 320]]


In [27]:
##Q3.5: Extract rows 3 to 7 (inclusive)

rows_3_to_7 = banking_data[3:8]
print(rows_3_to_7)

[]


Question 4: Mathematical Operations

In [29]:
##Q4.1: Calculate the sum of all account balances

sum_of_account_balances = np.sum(banking_data[:, 1])
print(sum_of_account_balances)

670


In [30]:
##Q4.2: Calculate the mean account balance

mean_account_balance = np.mean(banking_data[:, 1])
print(mean_account_balance)


223.33333333333334


In [31]:
##Q4.3: Calculate the standard deviation of account balances

std_acc_bal = np.std(banking_data[:,1])
print(std_acc_bal)

20.548046676563256


In [32]:
##Q4.4: Calculate the variance of account balances

var_acc_bal = np.var(banking_data[:,1])
print(var_acc_bal)

422.22222222222223


In [33]:
##Q4.5: Calculate the median account balance

median_acc_bal = np.median(banking_data[:,1])
print(median_acc_bal)

220.0


Question 5: Statistical Functions

In [34]:
##Q5.1: Find the minimum and maximum account balances

min_acc_bal = np.min(banking_data[:,1])
max_acc_bal = np.max(banking_data[:,1])
print(f"Minimum Account Balance: {min_acc_bal}")
print(f"Maximum Account Balance: {max_acc_bal}")

Minimum Account Balance: 200
Maximum Account Balance: 250


In [35]:
##Q5.2: Find the minimum and maximum credit scores

min_credit_score = np.min(banking_data[:,2])
max_credit_score = np.max(banking_data[:,2])
print(f"Minimum Credit Score: {min_credit_score}")
print(f"Maximum Credit Score: {max_credit_score}")

Minimum Credit Score: 300
Maximum Credit Score: 350


In [37]:
from os.path import basename
##Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

percentile_25 = np.percentile(banking_data[:,1], 25)
percentile_50 = np.percentile(banking_data[:,1], 50)
percentile_75 = np.percentile(banking_data[:,1], 75)
print(f"25th Percentile: {percentile_25}")
print(f"50th Percentile: {percentile_50}")
print(f"75th Percentile: {percentile_75}")

25th Percentile: 210.0
50th Percentile: 220.0
75th Percentile: 235.0


In [39]:
##Q5.4: Calculate the correlation between account balance and credit score

correlation = np.corrcoef(banking_data[:,1], banking_data[:,2])[0,1]
print(f"Correlation: {correlation}")

Correlation: 1.0


In [40]:
##Q5.5: Calculate the covariance between account balance and credit score

covariance = np.cov(banking_data[:,1], banking_data[:,2])[0,1]
print(covariance)

633.3333333333334


Question 6: Array Reshaping and Manipulation

In [42]:
##Q6.1: Reshape the banking_data to 5 rows × 10 columns

reshaped_data = banking_data.reshape(3,3)
print(reshaped_data)

[[100 200 300]
 [150 250 350]
 [120 220 320]]


In [43]:
##Q6.2: Flatten the banking_data to a 1D array

flattened_data = banking_data.flatten()
print(flattened_data)

[100 200 300 150 250 350 120 220 320]


In [44]:
##Q6.3: Transpose the banking_data

transposed_data = banking_data.T
print(transposed_data)

[[100 150 120]
 [200 250 220]
 [300 350 320]]


In [45]:
##Q6.4: Split the banking_data into 2 equal parts vertically

split_data = np.array_split(banking_data, 2)
print(split_data)

[array([[100, 200, 300],
       [150, 250, 350]]), array([[120, 220, 320]])]


In [46]:
##Q6.5: Split the banking_data into 2 equal parts horizontally

split_data = np.array_split(banking_data, 2, axis=1)
print(split_data)

[array([[100, 200],
       [150, 250],
       [120, 220]]), array([[300],
       [350],
       [320]])]


Question 7: Logical Operations and Filtering


In [47]:
##Q7.1: Find customers with account balance greater than $100,000

filtered_data = banking_data[banking_data[:,1] > 100000]
print(filtered_data)

[]


In [48]:
##Q7.2: Find customers with credit score greater than 800

filtered_data = banking_data[banking_data[:,2] > 800]
print(filtered_data)

[]


In [49]:
##Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

filtered_data = banking_data[(banking_data[:, 0] > 50) & (banking_data[:, 2] < 750)]
print(filtered_data)

[[100 200 300]
 [150 250 350]
 [120 220 320]]


In [50]:
##Q7.4: Count how many customers have account balance between $10,000 and $100,000

filtered_customers = banking_data[(banking_data[:, 1] > 10000) & (banking_data[:, 1] < 100000)]
count_customers = filtered_customers.shape[0]
print(f"Number of customers with account balance between $10,000 and $100,000: {count_customers}")

Number of customers with account balance between $10,000 and $100,000: 0


In [52]:
##Q7.5: Find the index of the customer with the highest credit score

highest_credit_score_index = np.argmax(banking_data[:, 2])
print(f"highest_credit_score_index :{highest_credit_score_index}")

highest_credit_score_index :1


Question 8: Sorting and Searching

In [53]:
##Q8.1: Sort the banking_data by account balance (ascending)

sorted_data = banking_data[banking_data[:, 1].argsort()]
print(sorted_data)

[[100 200 300]
 [120 220 320]
 [150 250 350]]


In [54]:
##Q8.2: Sort the banking_data by credit score (descending)

sorted_data = banking_data[banking_data[:, 2].argsort()[::-1]]
print(sorted_data)

[[150 250 350]
 [120 220 320]
 [100 200 300]]


In [55]:
##Q8.2: Sort the banking_data by credit score (descending)

sorted_data = banking_data[banking_data[:, 2].argsort()[::-1]]
print(sorted_data)

[[150 250 350]
 [120 220 320]
 [100 200 300]]


In [56]:
##Q8.4: Find the customer with the second highest account balance

sorted_data = banking_data[banking_data[:, 1].argsort()[::-1]]
second_highest_account_balance = sorted_data[1]
print(second_highest_account_balance)

[120 220 320]


In [57]:
##Q8.5: Find the customer with the lowest transaction count

lowest_transaction_count = np.argmin(banking_data[:, 0])
print(lowest_transaction_count)

0


Question 9: Mathematical Functions

In [58]:
##Q9.1: Calculate the absolute values of all elements

absolute_values = np.abs(banking_data)
print(absolute_values)

[[100 200 300]
 [150 250 350]
 [120 220 320]]


In [59]:
##Q9.2: Calculate the square root of all account balances

sqrt_account_balances = np.sqrt(banking_data[:, 1])
print(sqrt_account_balances)

[14.14213562 15.8113883  14.83239697]


In [60]:
##Q9.3: Calculate the square of all credit scores

square_credit_scores = np.square(banking_data[:, 2])
print(square_credit_scores)

[ 90000 122500 102400]


In [62]:
##Q9.4: Calculate the exponential of all transaction counts

exp_transaction_counts = np.exp(banking_data[:, 0])
print(exp_transaction_counts)

[2.68811714e+43 1.39370958e+65 1.30418088e+52]


In [63]:
##Q9.5: Calculate the natural logarithm of all account balances

natural_acc = np.log(banking_data[:, 1])
print(natural_acc)

[5.29831737 5.52146092 5.39362755]


Question 10: Advanced Operations

In [64]:
##Q10.1: Calculate the cumulative sum of account balances

cumulative_sum_account_balances = np.cumsum(banking_data[:, 1])
print(cumulative_sum_account_balances)

[200 450 670]


In [66]:
##Q10.2: Calculate the cumulative product of transaction counts

cumulative_product_transaction_counts = np.cumprod(banking_data[:, 0])
print(cumulative_product_transaction_counts)

[    100   15000 1800000]


In [67]:
##Q10.2: Calculate the cumulative product of transaction counts

cumulative_product_transaction_counts = np.cumprod(banking_data[:, 0])
print(cumulative_product_transaction_counts)

[    100   15000 1800000]


In [68]:
##Q10.3: Calculate the difference between consecutive account balances

difference_account_balances = np.diff(banking_data[:, 1])
print(difference_account_balances)

[ 50 -30]


In [69]:
##Q10.4: Calculate the gradient of account balances

gradient_account_balances = np.gradient(banking_data[:, 1])
print(gradient_account_balances)

[ 50.  10. -30.]


In [70]:
##Q10.5: Calculate the histogram of account balances with 5 bins

histogram_account_balances = np.histogram(banking_data[:, 1], bins=5)
print(histogram_account_balances)

(array([1, 0, 1, 0, 1]), array([200., 210., 220., 230., 240., 250.]))


Question 11: Random Numbers and Simulation

In [71]:
##Q11.1: Generate 6 random integers between 1 and 1000

random_integers = np.random.randint(1, 1001, 6)
print(random_integers)

[ 53 126 148 659 987 367]


In [72]:
##Q11.2: Generate 6 random floats between 0 and 1

random_floats = np.random.rand(6)
print(random_floats)

[0.18499444 0.85179821 0.09265447 0.40795259 0.17166069 0.42730522]


In [73]:
##Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

random_normal = np.random.normal(700, 100, 6)
print(random_normal)

[832.24965326 559.98995004 565.45837871 728.03320023 651.4898175
 719.08265879]


In [74]:
##Q11.4: Shuffle the banking_data rows randomly

shuffled_data = np.random.shuffle(banking_data)
print(shuffled_data)

None


In [75]:
##Q11.5: Set random seed to 123 and generate 4 random numbers

np.random.seed(123)
random_numbers = np.random.rand(4)
print(random_numbers)

[0.69646919 0.28613933 0.22685145 0.55131477]


Question 12: Linear Algebra Operations

In [76]:
##Q12.1: Calculate the dot product of account balance and credit score columns

dot_product = np.dot(banking_data[:, 1], banking_data[:, 2])
print(dot_product)

217900


In [77]:
##Q12.2: Calculate the cross product of first two rows

cross_product = np.cross(banking_data[0], banking_data[1])
print(cross_product)

[  5000 -10000   5000]


In [79]:
##Q12.3: Calculate the norm (magnitude) of the account balance column

norm_account_balance = np.linalg.norm(banking_data[:, 1], axis=0)
print(norm_account_balance)

388.45849199110063


In [82]:
##Q12.4: Create a 3x3 matrix and calculate its determinant

matrix_determinant = np.linalg.det(banking_data)
print(matrix_determinant)

0.0


In [87]:
##Q12.5: Calculate the inverse of the 3x3 matrix

matrix_3x3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inverse_matrix = np.linalg.inv(matrix_3x3)
print(inverse_matrix)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


Question 13: String Operations

In [88]:
##Q13.1: Convert all customer IDs to strings

customer_ids = banking_data[:, 0].astype(str)
print(customer_ids)

['150' '100' '120']


In [90]:
##Q13.2: Check if any customer ID contains '100'

contains_100 = np.char.find(customer_ids, '100') != -1
print(contains_100)

[False  True False]


In [91]:
##Q13.3: Convert all customer IDs to uppercase (if they were strings)

uppercase_customer_ids = np.char.upper(customer_ids)
print(uppercase_customer_ids)

['150' '100' '120']


In [92]:
##Q13.4: Count the length of each customer ID string

length_customer_ids = np.char.str_len(customer_ids)
print(length_customer_ids)

[3 3 3]


In [93]:
##Q13.5: Replace '100' with 'CUST' in customer IDs

replaced_customer_ids = np.char.replace(customer_ids, '100', 'CUST')
print(replaced_customer_ids)

['150' 'CUST' '120']


Question 14: Date and Time Operations

In [95]:
##Q14.1: Convert years active to months

years_active = banking_data[:, 2]
months_active = years_active * 12
print(months_active)

[4200 3600 3840]


In [96]:
##Q14.2: Calculate the average years active

average_years_active = np.mean(years_active)
print(average_years_active)

323.3333333333333


In [97]:
##Q14.3: Find customers who have been active for more than 5 years

active_customers = years_active > 5
print(active_customers)

[ True  True  True]


In [98]:
##Q14.4: Calculate the total time all customers have been active (in years)

total_active_time = np.sum(years_active)
print(total_active_time)

970


In [99]:
##Q14.5: Find the customer with the shortest time active

shortest_active_time = np.min(years_active)
print(shortest_active_time)

300


Question 15: Advanced Array Operations

In [100]:
##Q15.1: Apply a function to calculate 5% interest on all account balances

interest_rate = 0.05
account_balances_with_interest = banking_data[:, 1] * (1 + interest_rate)
print(account_balances_with_interest)

[262.5 210.  231. ]


In [101]:
##Q15.2: Use np.where to categorize customers by balance ranges

balance_ranges = np.where(banking_data[:, 1] < 210, 'Low', np.where(banking_data[:, 1] < 240, 'Medium', 'High'))
print(balance_ranges)

['High' 'Low' 'Medium']


In [14]:
##Q15.3: Use np.select to categorize customers by credit score ranges
import numpy as np
credit_scores = np.array([520, 610, 690, 720, 810])

conditions = [
    credit_scores < 580,
    (credit_scores >= 580) & (credit_scores < 670),
    (credit_scores >= 670) & (credit_scores < 740),
    credit_scores >= 740
]

# Categories
choices = ['Poor', 'Fair', 'Good', 'Excellent']

# Apply np.select with an explicit string default value
credit_category = np.select(conditions, choices, default='Unknown')

print(credit_category)

['Poor' 'Fair' 'Good' 'Good' 'Excellent']


In [23]:
##Q15.4: Use np.piecewise to apply different interest rates based on balance

banking_data = np.array([[100, 200, 300], [150, 250, 350], [120, 220, 320]])

conditions = [
    banking_data[:, 1] < 210,
    (banking_data[:, 1] >= 210) & (banking_data[:, 1] < 240),
    banking_data[:, 1] >= 240
]

functions = [
    lambda x: x * (1 + 0.01),
    lambda x: x * (1 + 0.02),
    lambda x: x * (1 + 0.03)
]

account_balances_with_piecewise_interest = np.piecewise(banking_data[:, 1], conditions, functions)
print(account_balances_with_piecewise_interest)

[202 257 224]


Question 16: Array Concatenation and Stacking

In [26]:
##Q16.1: Concatenate two arrays horizontally using np.hstack()


array1_to_stack = np.array([[1, 2], [3, 4], [5, 6]])
array2_to_stack = np.array([[7], [8], [9]])

stacked_array = np.hstack((array1_to_stack, array2_to_stack))
print(stacked_array)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [27]:
##Q16.2: Concatenate two arrays vertically using np.vstack()

array1_to_stack = np.array([[1, 2], [3, 4], [5, 6]])
array2_to_stack = np.array([[7, 8], [9, 10], [11, 12]])

stacked_array = np.vstack((array1_to_stack, array2_to_stack))
print(stacked_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [29]:
##Q16.3: Concatenate arrays along a specific axis using np.concatenate()

array1_to_stack = np.array([[1, 2], [3, 4], [5, 6]])
array2_to_stack = np.array([[7,8], [9, 10], [11, 12]])

stacked_array = np.concatenate((array1_to_stack, array2_to_stack), axis=1)
print(stacked_array)

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [31]:
##Q16.4: Stack arrays depth-wise using np.dstack()

array1_dstack = np.array([[1, 2], [3, 4]])
array2_dstack = np.array([[5, 6], [7, 8]])

stacked_dstack = np.dstack((array1_dstack, array2_dstack))
print(stacked_dstack)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [33]:
##Q16.5: Create a column stack using np.column_stack()

array1_column = np.array([1, 2, 3])
array2_column = np.array([4, 5, 6])

column_stacked_array = np.column_stack((array1_column, array2_column))
print(column_stacked_array)

[[1 4]
 [2 5]
 [3 6]]
