In [1]:
import numpy as np
import pandas as pd

In [2]:
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [3]:
print("\nORIGINAL RETAIL DATA:")
print(retail_data)
print(f"\nData shape: {retail_data.shape}")
print(f"Data type: {retail_data.dtype}")



ORIGINAL RETAIL DATA:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Data shape: (10, 5)
Data type: float64


In [4]:
print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")

identity_matrix = np.eye(3)
print(identity_matrix)



Q1.1: Create a 3x3 identity matrix using np.eye()
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
print("\nQ1.2: Create an array of 10 zeros using np.zeros()")

zeros_array = np.zeros(10)
print(zeros_array)



Q1.2: Create an array of 10 zeros using np.zeros()
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print("\nQ1.3: Create an array of 5 ones using np.ones()")

ones_array = np.ones(5)
print(ones_array)


Q1.3: Create an array of 5 ones using np.ones()
[1. 1. 1. 1. 1.]


In [7]:
print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")

range_array = np.arange(10)
print(range_array)


Q1.4: Create an array with values from 0 to 9 using np.arange()
[0 1 2 3 4 5 6 7 8 9]


In [8]:
print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")

linspace_array = np.linspace(0, 10, 6)
print(linspace_array)


Q1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()
[ 0.  2.  4.  6.  8. 10.]


In [9]:
print("\nQ2.1: What is the shape of the retail_data array?")

print(f"Shape: {retail_data.shape}")


Q2.1: What is the shape of the retail_data array?
Shape: (10, 5)


In [10]:
print("\nQ2.2: What is the data type of the retail_data array?")

print(f"Data type: {retail_data.dtype}")


Q2.2: What is the data type of the retail_data array?
Data type: float64


In [11]:
print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")

print(f"Size: {retail_data.size}")



Q2.3: What is the size (total number of elements) of the retail_data array?
Size: 50


In [12]:
print("\nQ2.4: What is the number of dimensions of the retail_data array?")

print(f"Dimensions: {retail_data.ndim}")


Q2.4: What is the number of dimensions of the retail_data array?
Dimensions: 2


In [13]:
print("\nQ2.5: What is the memory size of the retail_data array in bytes?")

print(f"Memory size: {retail_data.nbytes} bytes")


Q2.5: What is the memory size of the retail_data array in bytes?
Memory size: 400 bytes


In [14]:
print("\nQ3.1: Extract the first row of retail_data")

first_row = retail_data[0]
print(first_row)


Q3.1: Extract the first row of retail_data
[1001.     29.99   45.      4.2    15.  ]


In [15]:
print("\nQ3.2: Extract the last row of retail_data")

last_row = retail_data[-1]
print(last_row)


Q3.2: Extract the last row of retail_data
[1010.     59.99   34.      4.4    10.  ]


In [16]:
print("\nQ3.3: Extract the Price column (column index 1)")

price_column = retail_data[:, 1]
print(price_column)



Q3.3: Extract the Price column (column index 1)
[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [17]:
print("\nQ3.4: Extract the first 3 rows and first 2 columns")

subset = retail_data[:3, :2]
print(subset)


Q3.4: Extract the first 3 rows and first 2 columns
[[1001.     29.99]
 [1002.     49.99]
 [1003.     19.99]]


In [18]:
print("\nQ3.5: Extract rows 2 to 5 (inclusive)")

rows_2_to_5 = retail_data[2:6]
print(rows_2_to_5)


Q3.5: Extract rows 2 to 5 (inclusive)
[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


In [20]:
print("\nQ4.1: Calculate the sum of all prices")

total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")



Q4.1: Calculate the sum of all prices
Total price: $481.90


In [22]:
print("\nQ4.2: Calculate the mean price")

mean_price = np.mean(retail_data[:, 1])
print(f"Mean price: ${mean_price:.2f}")


Q4.2: Calculate the mean price
Mean price: $48.19


In [24]:
print("\nQ4.3: Calculate the standard deviation of prices")

std_price = np.std(retail_data[:, 1])
print(f"Standard deviation of prices: ${std_price:.2f}")


Q4.3: Calculate the standard deviation of prices
Standard deviation of prices: $24.70


In [25]:
print("\nQ4.4: Calculate the variance of prices")

var_price = np.var(retail_data[:, 1])
print(f"Variance of prices: ${var_price:.2f}")


Q4.4: Calculate the variance of prices
Variance of prices: $609.96


In [26]:
print("\nQ4.5: Calculate the median price")

median_price = np.median(retail_data[:, 1])
print(f"Median price: ${median_price:.2f}")


Q4.5: Calculate the median price
Median price: $44.99


In [28]:
print("\nQ5.1: Find the minimum and maximum prices")

min_price = np.min(retail_data[:, 1])
max_price = np.max(retail_data[:, 1])
print(f"Minimum price: ${min_price:.2f}")
print(f"Maximum price: ${max_price:.2f}")


Q5.1: Find the minimum and maximum prices
Minimum price: $15.99
Maximum price: $89.99


In [29]:
print("\nQ5.2: Find the minimum and maximum quantities sold")

min_qty = np.min(retail_data[:, 2])
max_qty = np.min(retail_data[:, 2])
print(f"Minimum quantity: {min_qty}")
print(f"Maximum quantity: {max_qty}")



Q5.2: Find the minimum and maximum quantities sold
Minimum quantity: 12.0
Maximum quantity: 12.0


In [30]:
print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")

percentiles = np.percentile(retail_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")


Q5.3: Calculate the percentile values for prices (25th, 50th, 75th)
25th percentile: $26.99
50th percentile: $44.99
75th percentile: $67.49


In [31]:
print("\nQ5.4: Calculate the correlation between prices and quantities sold")

correlation = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Correlation: {correlation:.4f}")


Q5.4: Calculate the correlation between prices and quantities sold
Correlation: -0.9291


In [32]:
print("\nQ5.5: Calculate the covariance between prices and quantities sold")

covariance = np.cov(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")


Q5.5: Calculate the covariance between prices and quantities sold
Covariance: -653.4444


In [33]:
print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")

reshaped_5x10 = retail_data.reshape(5, 10)
print(reshaped_5x10)


Q6.1: Reshape the retail_data to 5 rows × 10 columns
[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [34]:
print("\nQ6.2: Flatten the retail_data to a 1D array")

flattened = retail_data.flatten()
print(flattened)



Q6.2: Flatten the retail_data to a 1D array
[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]


In [35]:
print("\nQ6.3: Transpose the retail_data")

transposed = retail_data.T
print(transposed)


Q6.3: Transpose the retail_data
[[1001.   1002.   1003.   1004.   1005.   1006.   1007.   1008.   1009.
  1010.  ]
 [  29.99   49.99   19.99   89.99   15.99   69.99   39.99   79.99   25.99
    59.99]
 [  45.     32.     78.     12.     95.     28.     56.     18.     67.
    34.  ]
 [   4.2     4.5     3.8     4.7     4.      4.3     3.9     4.6     4.1
     4.4 ]
 [  15.      8.     22.      5.     18.     12.     20.      7.     16.
    10.  ]]


In [36]:
print("\nQ6.4: Split the retail_data into 2 equal parts vertically")

split_vertical = np.vsplit(retail_data, 2)
print("First part:")
print(split_vertical[0])
print("\nSecond part:")
print(split_vertical[1])


Q6.4: Split the retail_data into 2 equal parts vertically
First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [38]:
print("\nQ6.5: Split the retail_data into 2 equal parts horizontally")


split_horizontal = np.array_split(retail_data, 2, axis=1)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])


Q6.5: Split the retail_data into 2 equal parts horizontally
First part:
[[1001.     29.99   45.  ]
 [1002.     49.99   32.  ]
 [1003.     19.99   78.  ]
 [1004.     89.99   12.  ]
 [1005.     15.99   95.  ]
 [1006.     69.99   28.  ]
 [1007.     39.99   56.  ]
 [1008.     79.99   18.  ]
 [1009.     25.99   67.  ]
 [1010.     59.99   34.  ]]

Second part:
[[ 4.2 15. ]
 [ 4.5  8. ]
 [ 3.8 22. ]
 [ 4.7  5. ]
 [ 4.  18. ]
 [ 4.3 12. ]
 [ 3.9 20. ]
 [ 4.6  7. ]
 [ 4.1 16. ]
 [ 4.4 10. ]]


In [40]:
print("\nQ7.1: Find products with price greater than $50")

expensive_products = retail_data[retail_data[:, 1] > 50]
print(expensive_products)


Q7.1: Find products with price greater than $50
[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [41]:
print("\nQ7.2: Find products with customer rating greater than 4.0")

high_rated = retail_data[retail_data[:, 3] > 4.0]
print(high_rated)


Q7.2: Find products with customer rating greater than 4.0
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [42]:
print("\nQ7.3: Find products with quantity sold greater than 50 AND price less than $40")

popular_affordable = retail_data[(retail_data[:, 2] > 50) & (retail_data[:, 1] < 40)]
print(popular_affordable)


Q7.3: Find products with quantity sold greater than 50 AND price less than $40
[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [43]:
print("\nQ7.4: Count how many products have price between $20 and $60")

price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")



Q7.4: Count how many products have price between $20 and $60
Products in $20-$60 range: 5


In [44]:
print("\nQ7.5: Find the index of the product with the highest rating")

highest_rating_idx = np.argmax(retail_data[:, 3])
print(f"Index: {highest_rating_idx}, Product ID: {retail_data[highest_rating_idx, 0]}")


Q7.5: Find the index of the product with the highest rating
Index: 3, Product ID: 1004.0


In [47]:
print("\nQ8.1: Sort the retail_data by price (ascending)")

sorted_by_price = retail_data[retail_data[:, 1].argsort()]
print(sorted_by_price)


Q8.1: Sort the retail_data by price (ascending)
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [48]:
print("\nQ8.2: Sort the retail_data by quantity sold (descending)")

sorted_by_qty_desc = retail_data[(-retail_data[:, 2]).argsort()]
print(sorted_by_qty_desc)


Q8.2: Sort the retail_data by quantity sold (descending)
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [49]:
print("\nQ8.3: Find the indices that would sort the array by customer rating")

rating_sort_indices = np.argsort(retail_data[:, 3])
print(rating_sort_indices)


Q8.3: Find the indices that would sort the array by customer rating
[2 6 4 8 0 5 9 1 7 3]


In [50]:
print("\nQ8.4: Find the product with the second highest price")

second_highest_price_idx = np.argsort(retail_data[:, 1])[-2]
second_highest_product = retail_data[second_highest_price_idx]
print(f"Product ID: {second_highest_product[0]}, Price: ${second_highest_product[1]:.2f}")


Q8.4: Find the product with the second highest price
Product ID: 1008.0, Price: $79.99


In [51]:
print("\nQ8.5: Find the product with the lowest quantity sold")

lowest_qty_idx = np.argmin(retail_data[:, 2])
lowest_qty_product = retail_data[lowest_qty_idx]
print(f"Product ID: {lowest_qty_product[0]}, Quantity: {lowest_qty_product[2]}")


Q8.5: Find the product with the lowest quantity sold
Product ID: 1004.0, Quantity: 12.0


In [52]:
print("\nQ9.1: Calculate the absolute values of all elements")

absolute_values = np.abs(retail_data)
print(absolute_values)



Q9.1: Calculate the absolute values of all elements
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [53]:
print("\nQ9.2: Calculate the square root of all prices")

sqrt_prices = np.sqrt(retail_data[:, 1])
print(sqrt_prices)


Q9.2: Calculate the square root of all prices
[5.47631263 7.07036067 4.47101778 9.48630592 3.9987498  8.36600263
 6.3237647  8.94371288 5.09803884 7.74532117]


In [54]:
print("\nQ9.3: Calculate the square of all quantities sold")

squared_qty = np.square(retail_data[:, 2])
print(squared_qty)


Q9.3: Calculate the square of all quantities sold
[2025. 1024. 6084.  144. 9025.  784. 3136.  324. 4489. 1156.]


In [55]:
print("\nQ9.4: Calculate the exponential of all customer ratings")

exp_ratings = np.exp(retail_data[:, 3])
print(exp_ratings)


Q9.4: Calculate the exponential of all customer ratings
[ 66.68633104  90.0171313   44.70118449 109.94717245  54.59815003
  73.6997937   49.40244911  99.48431564  60.3402876   81.45086866]


In [56]:
print("\nQ9.5: Calculate the natural logarithm of all prices")

log_prices = np.log(retail_data[:, 1])
print(log_prices)


Q9.5: Calculate the natural logarithm of all prices
[3.40086399 3.91182299 2.99523215 4.49969855 2.77196353 4.24835237
 3.68862942 4.38190163 3.25771185 4.09417788]


In [57]:
print("\nQ10.1: Calculate the cumulative sum of prices")

cumsum_prices = np.cumsum(retail_data[:, 1])
print(cumsum_prices)



Q10.1: Calculate the cumulative sum of prices
[ 29.99  79.98  99.97 189.96 205.95 275.94 315.93 395.92 421.91 481.9 ]


In [58]:
print("\nQ10.2: Calculate the cumulative product of quantities sold")

cumprod_qty = np.cumprod(retail_data[:, 2])
print(cumprod_qty)


Q10.2: Calculate the cumulative product of quantities sold
[4.50000000e+01 1.44000000e+03 1.12320000e+05 1.34784000e+06
 1.28044800e+08 3.58525440e+09 2.00774246e+11 3.61393644e+12
 2.42133741e+14 8.23254720e+15]


In [59]:
print("\nQ10.3: Calculate the difference between consecutive prices")

diff_prices = np.diff(retail_data[:, 1])
print(diff_prices)



Q10.3: Calculate the difference between consecutive prices
[ 20. -30.  70. -74.  54. -30.  40. -54.  34.]


In [60]:
print("\nQ10.4: Calculate the gradient of prices")

gradient_prices = np.gradient(retail_data[:, 1])
print(gradient_prices)


Q10.4: Calculate the gradient of prices
[ 20.  -5.  20.  -2. -10.  12.   5.  -7. -10.  34.]


In [61]:
print("\nQ10.5: Calculate the histogram of prices with 5 bins")

hist_prices, bin_edges = np.histogram(retail_data[:, 1], bins=5)
print(f"Histogram counts: {hist_prices}")
print(f"Bin edges: {bin_edges}")



Q10.5: Calculate the histogram of prices with 5 bins
Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]


In [62]:
print("\nQ11.1: Generate 5 random integers between 1 and 100")

random_ints = np.random.randint(1, 101, 5)
print(random_ints)



Q11.1: Generate 5 random integers between 1 and 100
[35 81 58 59 63]


In [63]:
print("\nQ11.2: Generate 5 random floats between 0 and 1")

random_floats = np.random.random(5)
print(random_floats)


Q11.2: Generate 5 random floats between 0 and 1
[0.48237452 0.64137995 0.85595651 0.77019208 0.01267462]


In [64]:
print("\nQ11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)")

normal_random = np.random.normal(0, 1, 5)
print(normal_random)


Q11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)
[ 0.57280651  0.94331117 -1.01662245 -0.70348888 -0.22246658]


In [65]:
print("\nQ11.4: Shuffle the retail_data rows randomly")

shuffled_data = retail_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)


Q11.4: Shuffle the retail_data rows randomly
[[1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [66]:
print("\nQ11.5: Set random seed to 42 and generate 3 random numbers")

np.random.seed(42)
seeded_random = np.random.random(3)
print(seeded_random)


Q11.5: Set random seed to 42 and generate 3 random numbers
[0.37454012 0.95071431 0.73199394]
